name: chromatophore
description: A customizable syntax highlighter.
environment:
  sdk: '>=2.12.0-133.6.beta <3.0.0'
dependencies:
  charcode: ^1.1.3
  markdown: ^4.0.0
  string_scanner: ^1.0.5
dev_dependencies:
  path: ^1.8.0
  test: ^1.16.3
